### ISSUE TITLE
Side brush and main brush hours left and percentage values seems to be swapped

### ISSUE THREAD

**Issue by kodifan** [marotoweb/home-assistant-vacuum-viomise#10]
Hello again.

I noticed that probably values for main and side brush are swapped. 
I know that id's for mapping those sensors are taken form specification file and seems to be correct but results show swapped values. 
I can swap it in sensors.yaml file and that is wthat i recently did, but it is little confusing. 
Here is my sensors.yaml configuration and screenshots from Mi Home App and Home Assistant   

      **vacuum_cleanmainbrush_h:
        friendly_name: Vacuum - Main brush hours
        unit_of_measurement: 'h'
        value_template: ' {{states.vacuum.viomise.attributes.main_brush_left}}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleanmainbrush_p:
        friendly_name: Vacuum - Main brush percentage
        unit_of_measurement: '%'
        value_template: ' {{(states.vacuum.viomise.attributes.main_brush_percentage) }}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleansidebrush_h:
        friendly_name: Vacuum - Side brush hours
        unit_of_measurement: 'h'
        value_template: ' {{states.vacuum.viomise.attributes.side_brush_left }}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleansidebrush_p:
        friendly_name: Vacuum - Side brush percentage
        unit_of_measurement: '%'
        value_template: ' {{(states.vacuum.viomise.attributes.side_brush_percentage)}} '
        icon_template: 'mdi:screwdriver'**
 

![Screenshot_20210516-131616_Mi Home](https://user-images.githubusercontent.com/7819312/118398536-5cc9b680-b659-11eb-9365-78499a69fd61.jpg)

![sensors](https://user-images.githubusercontent.com/7819312/118398527-53404e80-b659-11eb-82f0-495b0f9e18ee.png)

**Comment by marotoweb** [comment]
My mistake, fixed in https://github.com/marotoweb/home-assistant-vacuum-viomise/commit/fa8d48a89dbde9fce7bf2359920d6bc2d58e03db

**Comment by kodifan** [comment]
Thanks now everything is ok :)
