### ISSUE TITLE
Vacuum token on rebranded viomi

### ISSUE THREAD

**Issue by haze1986** [marotoweb/home-assistant-vacuum-viomise#11]
Hi do you know if we can obtain the token from rebranded viomi? The name is minihelpers hydra S7 and it has its own app thus I am not sure if the token can be extracted at all. 

Thanks

**Comment by marotoweb** [comment]
I'm not aware of other methods besides those available at https://www.home-assistant.io/integrations/xiaomi_miio/#retrieving-the-access-token
