### ISSUE TITLE
Issue with Viomi S9 SE

### ISSUE THREAD

**Issue by cheard** [marotoweb/home-assistant-vacuum-viomise#14]
```
 File "/config/custom_components/viomise/vacuum.py", line 457, in update
    state.append(d['value'])
KeyError: 'value'
```

I am receiving the following error in HA when trying to connect the Viomi S9. 

Is there a solution for this?

**Comment by marotoweb** [comment]
This integration only supports SE version or viomi.vacuum.v19

tTry to use another integration like Xiaomi Miot Auto
