### ISSUE TITLE
Not availabe in HACS

### ISSUE THREAD

**Issue by PieterGoossens** [marotoweb/home-assistant-vacuum-viomise#2]
Hi, thanks for creating this! The README says to install it with HACS. However, I'm not available to find it within the HACS' repositories. Any ideas?

**Comment by marotoweb** [comment]
You have to add my repository manually to HACKS

**Comment by marotoweb** [comment]
Go to the HACS integrations page and in the top right corner of the page click on the 3 points and choose "Custom repositories"
Add this repo "https://github.com/marotoweb/home-assistant-vacuum-viomise" and choose "Integration"  in category

**Comment by marotoweb** [comment]
I updated the information on how to install the component to be more accurate
