### ISSUE TITLE
Unsupported Viomi SE

### ISSUE THREAD

**Issue by Cigareoc** [marotoweb/home-assistant-vacuum-viomise#24]
Good evening! I have this robot for the last 1.5 years Viomi SE V-RVCLM21A,it worked very well until half a year ago through the integrations Viomi Robot Vacuum Cleaner SE (V-RVCLM21A),but now it doesn't work anymore,the integration is no longer supported?

**Comment by brano1990** [comment]
doesn't work last update

**Comment by Cigareoc** [comment]
> doesn't work last update

and how do you use it now?

**Comment by brano1990** [comment]
I updated the new HA yesterday , it doesn't work for me since yesterday

**Comment by Cigareoc** [comment]
> I updated the new HA yesterday , it doesn't work for me since yesterday

already for more than half a year it does not work for me with this integration

**Comment by brano1990** [comment]
I controlled it every weekend via HA, I will try to update it soon

I only use commands

room kitchen etc

the information about changing the brush etc. does not work, but I do not need it

**Comment by Cigareoc** [comment]
> I controlled it every weekend via HA, I will try to update it soon
> 
> I only use commands
> 
> room kitchen etc
> 
> the information about changing the brush etc. does not work, but I do not need it

give me an example of a command that sends

**Comment by brano1990** [comment]
it doesn't work for me anymore

at all

does it work for anyone?

**Comment by m33ts4k0z** [comment]
Hello.

This integration still works perfectly fine with all the information and controls. Using the latest HA OS 10.1 and HACS.
