### ISSUE TITLE
This entity does not have a unique ID

### ISSUE THREAD

**Issue by rufik** [marotoweb/home-assistant-vacuum-viomise#4]
HA complains about no unique ID for vacuum entity:
![image](https://user-images.githubusercontent.com/425558/107970087-f3320180-6fb0-11eb-9a6a-6c6904c5a868.png)

https://www.home-assistant.io/faq#this-entity-does-not-have-a-unique-id

Could it be fixed, please? :)

**Comment by marotoweb** [comment]
Thanks for your feedback.  It is not exactly an error, but just a limitation of the integration that already existed in the original.  What do you intend to configure in this integration?

**Comment by rufik** [comment]
Having Unique ID primary means that entity can be edited in UI i.e.:

![image](https://user-images.githubusercontent.com/425558/108093002-8a648b00-707d-11eb-89fe-76558e898c08.png)

It's **very** nice feature :) Second, it's advisable to follow HA developers guide...

**Comment by marotoweb** [comment]
Added based on the device's mac address

**Comment by rufik** [comment]
Very nice, thank you!
