### ISSUE TITLE
Cleaning map in HA

### ISSUE THREAD

**Issue by rufik** [marotoweb/home-assistant-vacuum-viomise#5]
Is it possible to download current map from vacuum? It would be nice to show it in HA, choose single/multiple rooms to be cleaned, show vacuuming progress in the map, just like in Xiaomi Home app ;)

**Comment by marotoweb** [comment]
The functionality you describe is excellent and it would be the best we could have, but it is far from the objective of this simple integration.  At this point it is possible through scripts to send the vacuum to clean multiple rooms or use the Google assistant to run these scripts but it is not possible to define a specific cleaning point or area.

**Comment by rufik** [comment]
Sending vacuum to room(s) is very sufficient, script is also fine. There is no need for point/area, personally I've never used it. Could you an example, please?

What about showing map and cleaning progress?

**Comment by marotoweb** [comment]
For script you can check this topic
https://community.home-assistant.io/t/xiaomi-viomi-v1-v2-support/165531/8

There is currently no way to show the map.  As for progress, we only managed to obtain the s_time in operation and the s_area that is currently clean

With some adjustments you can add this card https://community.home-assistant.io/t/xiaomi-vacuum-cleaner-card/64456/45

![Screenshot_20210307-203854__01](https://user-images.githubusercontent.com/4264711/110254122-afb22e00-7f85-11eb-9f9a-dfe398d61747.jpg)

**Comment by marotoweb** [comment]
I think the Xiaomi Cloud Map Extractor addon is the must have
