### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by jovanotti25** [marotoweb/home-assistant-vacuum-viomise#6]
This integration dont show sensor of main brush?

**Comment by marotoweb** [comment]
Sorry for the delay.
Are you referring to the main brush, side brush and filter statistics?

**Comment by jovanotti25** [comment]
Yes brush, side Brush and filter statistics 

> Sorry for the delay.
> Are you referring to the main brush, side brush and filter statistics?

Yes main brush, side brush and filter statistics

**Comment by marotoweb** [comment]
There is currently no support, but it may be possible to integrate because it is possible to obtain this information from the vacuum cleaner

**Comment by marotoweb** [comment]
check out latest version and give some feedback

**Comment by jovanotti25** [comment]
Yes Its Works Thanks a lot
