### ISSUE TITLE
Can't see my device in HA

### ISSUE THREAD

**Issue by Cupra1979** [marotoweb/home-assistant-vacuum-viomise#8]
Hi there,

I installed the integration via HACS and added the configuration to configuration.yaml file as indicated in the instructions but I can't understand where I have to enter my Xiaomi Cloud username and password.

At today, I cannot see the entity in HA...how can I solve this?
Thank you very much in advance!

**Comment by marotoweb** [comment]
Hi,
This integration only requires the token of your vacuum cleaner, to obtain your token there are several ways, one that I recommend is the use of a token extractor script https://www.home-assistant.io/integrations/xiaomi_miio/#retrieving-the-access-token and normally this way requires you to enter your username and password of your xiaomi account to extract your tokens.

**Comment by Cupra1979** [comment]
Got it...thank you very much. I added the vacuum to HA, now I have to find out how to have a complete dashboard showing all of its features and controls.

Thanks again!
